### ISSUE TITLE
OSM Road Network Enhancement Efforts In San Fernando

### ISSUE THREAD

**Issue by GRABOSM** [GRABOSM/Grab-Data#23]
Hello Gowin,

We would start reviewing the road network in the city San Fernando starting 28th August
Basis the pre-analysis we did to identify the right imagery and offsets, we found that Bing is imagery used with an recently created offset.
hence we will use Bing as default imagery with appropriate offset distance - existing or newly created basis strava.  We will also use standard imagery to ensure there are no missing roads as for some areas standard seems to be more clear than bing imagery

Below is one example basis which we would want to use Bing as default imagery while reviewing road network for San Fernando city

Example - way 53809027
![image](https://user-images.githubusercontent.com/38514914/44569179-28ba5300-a797-11e8-8ee1-f55592b68539.png)
![image](https://user-images.githubusercontent.com/38514914/44569208-3a9bf600-a797-11e8-93da-cb21465c67bb.png)

Bing imagery is aligned to existing data as well as to strava
![image](https://user-images.githubusercontent.com/38514914/44569261-63bc8680-a797-11e8-8f74-78ce2f88a085.png)

Please suggest otherwise.

As always thanks for your time and guidance
Lavanya
Grab Team

**Comment by govvin** [comment]
Thank you for incorporating imagery offset alignment validation with [Strava heatmaps](https://www.strava.com/heatmap) and the [IODb](http://offsets.textual.ru/map) in your work flow. This will make it convenient for other contributors and validators to replicate your offsets and setup. 

The [local mailing list](https://lists.openstreetmap.org/pipermail/talk-ph/) subscribers would appreciate it you can update them of your intentions, since it's considered the official channel for important communications.

**Comment by GRABOSM** [comment]
Hello Govvin,

Closing this thread as we are done with this city
Thanks for your guidance

Thanks
Lavanya
