### ISSUE TITLE
OSM Road Network Enhancement Effort In Binalonan

### ISSUE THREAD

**Issue by GRABOSM** [GRABOSM/Grab-Data#24]
Hello Gowin,

We would start reviewing the road network in the city Binalonan starting 28th August
Basis the pre-analysis we did to identify the right imagery and offsets, we found that Digi Globe Standard is aligned to ground truth when compared to Bing

Hence we will use Digi Globe Standard as default imagery with appropriate offset distance - existing or newly created basis strava. 
We will also use Bing imagery to ensure there are no missing roads as appropriate

Here is an example way id comparing with both the images - 
Way 43926953

Existing data has offset to Bing
![image](https://user-images.githubusercontent.com/38514914/44569652-bc405380-a798-11e8-84f9-e7a20f4a78c6.png)

Same area without offset when referred to Digi Standard Imagery
![image](https://user-images.githubusercontent.com/38514914/44569702-df6b0300-a798-11e8-8f36-3c23a80519c9.png)

Please suggest otherwise
Thanks
Lavanya
Grab Team

**Comment by govvin** [comment]
Thank you for incorporating imagery offset alignment validation with [Strava heatmaps](https://www.strava.com/heatmap) and the [IODb](http://offsets.textual.ru/map) in your work flow. This will make it convenient for other contributors and validators to replicate your offsets and setup. 

The [local mailing list](https://lists.openstreetmap.org/pipermail/talk-ph/) subscribers would appreciate it you can update them of your intentions, since it's considered the official channel for important communications.

**Comment by GRABOSM** [comment]
Hello Govvin,

Closing this thread as we are done with this city.  Thanks for your guidance

Thanks
Lavanya
